version: '3'
services:
  db:
    image: mariadb:10.3
    env_file:
      - ./docker-mysql.settings
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docroot:/var/www/html
    restart: always